# Generated by Django 5.0.6 on 2024-10-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documentos_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='duracion',
            field=models.FloatField(default=1.0, help_text='Duración del evento en horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='tamano',
            field=models.IntegerField(default=1.0, help_text='Número de asistentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_actividades',
            field=models.CharField(default=1.0, help_text='Descripción de las actividades', max_length=250),
            preserve_default=False,
        ),
    ]
